### PR TITLE
Shayan/update docs

### PR DESCRIPTION
**Pull request by shayanc1985**

### CODE REVIEW

**Comment by noahhoffman** [comment]
@shayanc1985 I think all of the sample code for /status is repetitive, maybe there's a way to refactor it out and point to it

**Comment by shayanc1985** [comment]
Right, let me figure out how to refactor that into a single section and add hyperlinks to that in all the API sections.

**Comment by shayanc1985** [comment]
@noahhoffman I have made the changes yo suggested. Please have a look.

**Comment by noahhoffman** [comment]
@shayanc1985 do we want to add a link to https://www.adobe.io/authentication/auth-methods.html#!AdobeDocs/adobeio-auth/master/AuthenticationOverview/AuthenticationGuide.md in the Authentication section?

**Comment by noahhoffman** [comment]
👍

**Pull request merged**
